### ISSUE TITLE
java.lang.UnsatisfiedLinkError: shadow.com.sun.jna.Native.getNativeVersion()Ljava/lang/String;

### ISSUE THREAD

**Issue by redslime** [MinnDevelopment/Java-DiscordRPC#12]
```
Caught exception from mcctfdiscordhook java.lang.UnsatisfiedLinkError: shadow.com.sun.jna.Native.getNativeVersion()Ljava/lang/String;
 	at shadow.com.sun.jna.Native.getNativeVersion(Native Method)
 	at shadow.com.sun.jna.Native.<clinit>(Native.java:192)
 	at shadow.club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
 	at main.java.redsli.me.mcctfdiscordhook.runnables.DiscordPresenceUpdater.<init>(DiscordPresenceUpdater.java:21)
```
Line 21: ```lib = DiscordRPC.INSTANCE;```

I'm shadowing the jar with [this](https://github.com/johnrengelman/shadow) gradle plugin, not sure if relevant or not.

**Comment by MinnDevelopment** [comment]
Is there a reason to relocate jna or this library?

**Comment by redslime** [comment]
I tried not shadowing/relocating the library, problem persists.

**Comment by MinnDevelopment** [comment]
This sounds more like an issue with the JNA version you're using.
