### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by hbarreau** [MinnDevelopment/Java-DiscordRPC#28]
Hi, I have a problem.
When I run the program, my window opens. But an error appears in the console : 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (win32-x86-64/discord-rpc.dll) not found in resource path ([file:/C:/Program%20Files/Java/jre1.8.0_181/lib/resources.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/rt.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/jsse.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/jce.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/charsets.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/jfr.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jre1.8.0_181/lib/ext/zipfs.jar, file:/C:/Users/Hugo/Desktop/Developpement/Java/WorkSpace/RichPresenceApp/bin/, file:/C:/Users/Hugo/Desktop/Developpement/Java/API/Discord/java-discord-rpc-2.0.1.jar, file:/C:/Users/Hugo/Desktop/Developpement/Java/API/Discord/jna-4.5.2.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at fr.hugogame18.richpresenceapp.MainRich.main(MainRich.java:18)
```

Code : 

```java
package fr.hugogame18.richpresenceapp;

import javax.swing.JFrame;

import club.minnced.discord.rpc.DiscordEventHandlers;
import club.minnced.discord.rpc.DiscordRPC;
import club.minnced.discord.rpc.DiscordRichPresence;

public class MainRich {

    public static Thread t;

    public static void main(String[] args) {

        JFrame fen = new FrameBot();

        DiscordRichPresence presence = new DiscordRichPresence();
        DiscordRPC lib = DiscordRPC.INSTANCE;
        String applicationId = "122";

        DiscordEventHandlers handlers = new DiscordEventHandlers();
        handlers.ready = (user) -> System.out.println("Ready!");

        lib.Discord_Initialize(applicationId, handlers, true, null);

        presence.startTimestamp = System.currentTimeMillis() / 1000; // epoch second
        presence.endTimestamp = presence.startTimestamp + 20;
        presence.details = "Details here";
        presence.state = "State here";
        presence.partySize = 1;
        presence.partyMax = 4;
        lib.Discord_UpdatePresence(presence);

        t = new Thread(() -> {
            while (!Thread.currentThread().isInterrupted()) {
                lib.Discord_RunCallbacks();
                try {
                    Thread.sleep(500);
                } catch (InterruptedException e) {
                    lib.Discord_Shutdown();
                    break;
                }
            }
        }, "RPC-Callback-Handler");
        t.start();

    }

}
```

**Comment by m-sterling** [comment]
Hey there, you need to add the native binaries to your resource path in order to hook into the Discord client. I noticed you're using Windows, but what IDE are you using?

**Comment by hbarreau** [comment]
I use Eclipse IDE. I add native in this ? : 
![capture](https://user-images.githubusercontent.com/23046817/44049828-7fd7491e-9f35-11e8-97d0-f352f6823973.PNG)

**Comment by hbarreau** [comment]
I added discord-rpc.dll and it worked well. Thank you
