### ISSUE TITLE
Unable to load library 'discord-rpc' Minecraft 1.8.8 MCP Error

### ISSUE THREAD

**Issue by Suzakii** [MinnDevelopment/Java-DiscordRPC#40]
Hello, I have a problem, when i use the library in Minecraft MCP 1.8 (mcp910-pre1) that's work, but, if i want use it in Minecraft MCP 1.8.8 (MCP918), when minecraft start i have that's error:

> ---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 02/05/19 21:30
Description: Initializing game

java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Le module spécifié est introuvable.

	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:368)
	at com.sun.jna.Native.loadLibrary(Native.java:353)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at aroz.main.Discord.startDiscord(Discord.java:14)
	at aroz.main.Client.startClient(Client.java:25)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:590)
	at net.minecraft.client.Minecraft.run(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:368)
	at com.sun.jna.Native.loadLibrary(Native.java:353)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at aroz.main.Discord.startDiscord(Discord.java:14)
	at aroz.main.Client.startClient(Client.java:25)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:590)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:11)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 920649504 bytes (877 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: mcp
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\mathe\Desktop\Aroz-CM\mods1.8.8\jars\.\crash-reports\crash-2019-05-02_21.30.12-client.txt
[21:30:12] [Client Shutdown Thread/INFO]: Stopping server
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

You have any idea ? And sorry for my bad English, i'm french.

**Comment by MinnDevelopment** [comment]
I have answered an identical issue at #30 

The problem here is directly related to your specific setup and compilation process and I am unable to help with that. You didn't provide any details about compilation of your project or how you link with this library. A common pitfall here would be an outdated version of JNA or a missing transitive dependency.

**Comment by MinnDevelopment** [comment]
Closing since this issue is stale and there is nothing I can do for it to be resolved.
